# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create(name: '公式サイト', slug: 'official', description: '公式サイトからの情報', sort_key: 10)
Category.create(name: 'まとめブログ', slug: 'matome', description: '2chまとめブログからの情報', sort_key: 5)
Category.create(name: '声優ブログ', slug: 'actor', description: '声優さんのブログ', sort_key: 1)

Feed.create(title: 'アイマス公式', category_id: 1, feed_url: 'http://idolmaster.jp/blog/?feed=rss2')
Feed.create(title: 'みります！', category_id: 2, feed_url: 'http://millimas.net/index.rdf')
Feed.create(title: 'ミリオンライブニュース', category_id: 2, feed_url: 'http://imasmillionlive.blog.fc2.com/?xml')
Feed.create(title: 'ヴァイ', category_id: 2, feed_url: 'http://vaimas.blog.fc2.com/?xml')
Feed.create(title: 'えりこさん', category_id: 3, feed_url: 'http://rssblog.ameba.jp/eriko-nakamura-blog/rss20.xml')
Feed.create(title: 'みんごす', category_id: 3, feed_url: 'http://blog.livedoor.jp/ubiquitous777/index.rdf')
Feed.create(title: 'あずみん', category_id: 3, feed_url: 'http://rssblog.ameba.jp/asakura-azumi/rss20.xml')
Feed.create(title: 'にごさん', category_id: 3, feed_url: 'http://yaplog.jp/maya-rhythm/index1_0.rdf')
Feed.create(title: 'わかばやしさん', category_id: 3, feed_url: 'http://wakachoku.way-nifty.com/blog/atom.xml')
Feed.create(title: 'ちあきんぐ', category_id: 3, feed_url: 'http://chiaking.officialblog.jp/atom.xml')
Feed.create(title: 'くぎみー', category_id: 3, feed_url: 'http://rssblog.ameba.jp/kugimiyarie-blog/rss20.xml')
Feed.create(title: 'ひらたさん', category_id: 3, feed_url: 'http://blog.livedoor.jp/hira__hiro/atom.xml')
Feed.create(title: 'あさぽん', category_id: 3, feed_url: 'http://yaplog.jp/asaponmax/index1_0.rdf')
Feed.create(title: 'あっきー', category_id: 3, feed_url: 'http://blog.livedoor.jp/onigiriwa315/atom.xml')
Feed.create(title: 'ぬーぬー', category_id: 3, feed_url: 'http://blog.livedoor.jp/mnm_n_/atom.xml')
Feed.create(title: 'はらみー', category_id: 3, feed_url: 'http://yaplog.jp/heavenly_cafe/index1_0.rdf')
Feed.create(title: 'じゅりあ', category_id: 3, feed_url: 'http://rssblog.ameba.jp/aimi-sound/rss20.xml')
Feed.create(title: 'ともかさん', category_id: 3, feed_url: 'http://rssblog.ameba.jp/koiwai-kotori/rss20.xml')
Feed.create(title: 'もがみん（ころあず）', category_id: 3, feed_url: 'http://rssblog.ameba.jp/azusa-tadokoro/rss20.xml')

Idol.create(fullname: '天海 春香', kana: 'あまみ はるか', age: 17)
Idol.create(fullname: '如月 千早', kana: 'きさらぎ ちはや', age: 16)
Idol.create(fullname: '星井 美希', kana: 'ほしい みき', age: 15)
Idol.create(fullname: '萩原 雪歩', kana: 'はぎわら ゆきほ', age: 17)
Idol.create(fullname: '高槻 やよい', kana: 'たかつき やよい', age: 14)
Idol.create(fullname: '菊地 真', kana: 'きくち まこと', age: 17)
Idol.create(fullname: '水瀬 伊織', kana: 'みなせ いおり', age: 15)
Idol.create(fullname: '四条 貴音', kana: 'しじょう たかね', age: 18)
Idol.create(fullname: '秋月 律子', kana: 'あきづき りつこ', age: 19)
Idol.create(fullname: '三浦 あずさ', kana: 'みうら あずさ', age: 21)
Idol.create(fullname: '双海 亜美', kana: 'ふたみ あみ', age: 13)
Idol.create(fullname: '双海 真美', kana: 'ふたみ まみ', age: 13)
Idol.create(fullname: '我那覇 響', kana: 'がなは ひびき', age: 16)
